[build-system]
requires = [
     # pin NumPy version used in the build, to avoid building against the latest
     # NumPy from PyPI (and potentially introducing ABI compatibilities with the
     # actual NumPy version in the environment)
     "numpy>=1.22; python_version<'3.10'",
     # don't pin version for as-yet-unreleased versions of Python
     "numpy>=1.18; python_version>'3.9'",
     "setuptools>=43.0.0"
]
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
